#!/usr/bin/env python3

import os
import sys

from PIL import Image
from PIL import ImageDraw





# ----- Test Function ----- #

def func_test (flags):
	print(flags)





# ----- Make Function ----- #

def func_make (flags):

	# --- Config --- #
	source_file  = 'Catppuccin.tsv'
	palette_name = 'Catppuccin'

	colour_circle_size         = 40
	png_palette_pixel_size     = 16
	palette_preview_height     = 70
	palette_preview_pixel_size = 40



	# --- Colour Storage --- #
	def func_make_read_source (source_file):

		print(f'Reading source file: {source_file}')

		# read storage file and remove empty lines
		source      = open(source_file)
		colour_list = [line for line in source.readlines() if line.strip()]
		source.close()

		# remove file header
		colour_list.pop(0)

		print(f'Processing {len(colour_list)} colours')

		# create internal colour storage
		colour_storage = list()
		for colour_entry in colour_list:

			# remove newline & split fields
			colour_entry = colour_entry.replace('\n', '')
			colour_data  = colour_entry.split('\t')

			# format data
			colour_name  = colour_data[0].lower()
			colour_hsl   = colour_data[3].replace(' ', '').split(',')

			# format HSL values
			colour_hue           = int(colour_hsl[0])
			colour_saturation    = int(colour_hsl[1].replace('%', ''))
			colour_lightness     = int(colour_hsl[2].replace('%', ''))
			colour_hsl_formatted = 'hsl(%d, %d%%, %d%%)' % (colour_hue, colour_saturation, colour_lightness)

			# push to internal colour storage
			colour_storage.append([colour_name, colour_hsl_formatted])

		return colour_storage



	# --- Preview Circles --- #
	def func_make_cirles (colour_storage, colour_count):

		# create export directory
		if not os.path.exists('circles'):
			os.makedirs('circles')


		# setup progessbar
		toolbar_width = colour_count
		sys.stdout.write('\nGenerating Circles\n[%s]' % (' ' * toolbar_width))
		sys.stdout.flush()
		sys.stdout.write('\b' * (toolbar_width+1))


		for colour in colour_storage:

			# create canvas
			circle_canvas = Image.new('RGBA', (colour_circle_size * 100, colour_circle_size * 100))

			# draw circle with current colour
			circle_canvas_draw = ImageDraw.Draw(circle_canvas)
			circle_canvas_draw.ellipse((0, 0, colour_circle_size * 100, colour_circle_size * 100), colour[1])

			# resize and export
			circle_colour_preview = circle_canvas.resize((colour_circle_size, colour_circle_size))
			circle_colour_preview.save(f'circles/{colour[0]}.png')

			# update progessbar
			sys.stdout.write('=')
			sys.stdout.flush()

		# end progressbar
		sys.stdout.write(']\n')



	# --- .png Palette --- #
	def func_make_palette (colour_storage, colour_count):

		# setup progessbar
		toolbar_width = colour_count
		sys.stdout.write('\nGenerating .png Palette\n[%s]' % (' ' * toolbar_width))
		sys.stdout.flush()
		sys.stdout.write('\b' * (toolbar_width+1))


		pixel_size   = png_palette_pixel_size
		current_spot = 0
		png_canvas   = Image.new('RGBA', (colour_count*pixel_size, pixel_size))


		for colour in colour_storage:

			# create canvas
			png_canvas_draw = ImageDraw.Draw(png_canvas)

			# draw pixel
			png_canvas_draw.rectangle(((current_spot, 0), (current_spot+pixel_size, pixel_size)), colour[1])

			# update pixel position
			current_spot = current_spot+pixel_size

			# update progessbar
			sys.stdout.write('=')
			sys.stdout.flush()


		# export
		png_canvas.save(f'{palette_name}.png')

		# end progressbar
		sys.stdout.write(']\n')



	# --- Themed Palettes --- #
	def func_make_themed (colour_storage):

		# strip colours
		morning_colours = ['flamingo', 'mauve', 'pink', 'maroon', 'red', 'peach', 'yellow', 'green', 'teal', 'blue', 'sky']
		night_colours   = ['rosewater', 'lavender', 'black0', 'black1', 'black2', 'black3', 'black4', 'gray0', 'gray1', 'gray2', 'white']
		morning_palette = {colour[0]:colour[1:] for colour in colour_storage if colour[0] in morning_colours}
		night_palette   = {colour[0]:colour[1:] for colour in colour_storage if colour[0] in night_colours}


		# prepare variables
		morning_colour_count  = len(morning_palette)
		night_colour_count    = len(night_palette)
		palette_height        = palette_preview_height * 100
		pixel_size            = palette_preview_pixel_size * 100
		pixel_padding         = (palette_height-pixel_size)/2
		morning_palette_width = int((morning_colour_count*(pixel_size+pixel_padding))-pixel_padding+palette_height/2)
		night_palette_width   = int((night_colour_count*(pixel_size+pixel_padding))-pixel_padding+palette_height/2)

		# create canvases
		morning_canvas = Image.new('RGBA', (morning_palette_width, palette_height))
		night_canvas   = Image.new('RGBA', (night_palette_width, palette_height))


		# - Morning Palette - #
		# setup progessbar
		toolbar_width = morning_colour_count
		sys.stdout.write('\nGenerating Morning Palette\n[%s]' % (' ' * toolbar_width))
		sys.stdout.flush()
		sys.stdout.write('\b' * (toolbar_width+1))


		# create background
		morning_canvas_draw = ImageDraw.Draw(morning_canvas)
		morning_canvas_draw.ellipse((0, 0, palette_height, palette_height), night_palette['black0'][0])
		morning_canvas_draw.ellipse((morning_palette_width-palette_height, 0, morning_palette_width, palette_height), night_palette['black0'][0])
		morning_canvas_draw.rectangle(((palette_height/2, 0), (morning_palette_width-palette_height/2, palette_height)), night_palette['black0'][0])


		# create circles
		current_spot = 0
		for colour in morning_palette:

			morning_canvas_draw.ellipse((pixel_padding+current_spot, pixel_padding, (palette_height-pixel_padding)+current_spot, palette_height-pixel_padding), morning_palette[colour][0])
			current_spot = current_spot+(palette_height-pixel_padding)

			# update progessbar
			sys.stdout.write('=')
			sys.stdout.flush()


		# resize and export
		morning_canvas_preview = morning_canvas.resize((int(morning_palette_width/100), palette_preview_height))
		morning_canvas_preview.save('morning.png')

		# end progressbar
		sys.stdout.write(']\n')


		# - Night Palette - #
		# setup progessbar
		toolbar_width = night_colour_count
		sys.stdout.write('\nGenerating Night Palette\n[%s]' % (' ' * toolbar_width))
		sys.stdout.flush()
		sys.stdout.write('\b' * (toolbar_width+1))


		# create background
		night_canvas_draw = ImageDraw.Draw(night_canvas)
		night_canvas_draw.ellipse((0, 0, palette_height, palette_height), night_palette['black0'][0])
		night_canvas_draw.ellipse((night_palette_width-palette_height, 0, night_palette_width, palette_height), night_palette['black0'][0])
		night_canvas_draw.rectangle(((palette_height/2, 0), (night_palette_width-palette_height/2, palette_height)), night_palette['black0'][0])


		# create circles
		current_spot = 0
		for colour in night_palette:

			night_canvas_draw.ellipse((pixel_padding+current_spot, pixel_padding, (palette_height-pixel_padding)+current_spot, palette_height-pixel_padding), night_palette[colour][0])
			current_spot = current_spot+(palette_height-pixel_padding)

			# update progessbar
			sys.stdout.write('=')
			sys.stdout.flush()


		# resize and export
		night_canvas_preview = night_canvas.resize((int(night_palette_width/100), palette_preview_height))
		night_canvas_preview.save('night.png')

		# end progressbar
		sys.stdout.write(']\n')





	# --- Sub Command Handler --- #

	# populate "globals"
	colour_storage = func_make_read_source(source_file)
	colour_count   = len(colour_storage)

	# --- Default --- #
	if len(flags) == 0 or any(flag in flags for flag in ('-a', '--all')):
		func_make_cirles(colour_storage, colour_count)
		func_make_palette(colour_storage, colour_count)
		func_make_themed(colour_storage)

		# exit if default action is run
		return

	# --- Circles --- #
	if any(flag in flags for flag in ('-c', '--circles')):
		func_make_cirles(colour_storage, colour_count)

	# --- Palette --- #
	if any(flag in flags for flag in ('-p', '--palette')):
		func_make_palette(colour_storage, colour_count)

	# --- Themed Palettes --- #
	if any(flag in flags for flag in ('-t', '--themed')):
		func_make_themed(colour_storage)





# ----- Command Handler ----- #

def command_handler (args):

	# remove self
	script_name = args.pop(0)


	# --- Help --- #
	if len(args) == 0 or any(arg in args for arg in ('-h', 'help')):

		print('\n--- Commands ---')
		print(f'Usage: {script_name} <command>')
		print()
		print('make              Generate Assets')
		print('  -a, --all       default; generates all assets')
		print('  -c, --circles   generate palette preview circles')
		print('  -p, --palette   generate .png palette file')
		print('  -t, --themed    generate morning & night palettes')
		print()
		print('help, --help      show this message')
		print()

		# terminate script if help is called
		return



	# --- Sub Commands --- #
	else:

		sub_command       = args.pop(0)
		sub_command_flags = args

		try:
			# execute sub command based on provided argument
			globals()[f'func_{sub_command}'](sub_command_flags)

		except:
			# if sub command doesn't exist throw error
			print(f'{sub_command} is not a valid sub command.')
			print(f'Try {script_name} help to get a list of all commands.')





# ----- Please Run Me ----- #

if __name__ == '__main__':
	command_handler(sys.argv)
