#!/usr/bin/env python3

import os
import sys

from PIL import Image
from PIL import ImageDraw





# ----- Colour Storage ----- #

def read_source ():

	source_file = 'colours.tsv'
	print(f'Reading source file: {source_file}')

	# read storage file and remove empty lines
	source      = open(source_file)
	colour_list = [line for line in source.readlines() if line.strip()]
	source.close()

	# remove file header
	colour_list.pop(0)

	print(f'Processing {len(colour_list)} colours')

	# create internal colour storage
	colour_storage = list()
	for colour_entry in colour_list:

		# remove newline & split fields
		colour_entry = colour_entry.replace('\n', '')
		colour_data  = colour_entry.split('\t')

		# format data
		colour_name  = colour_data[0].lower()
		colour_hsl   = colour_data[3].replace(' ', '').split(',')

		# format HSL values
		colour_hue           = int(colour_hsl[0])
		colour_saturation    = int(colour_hsl[1].replace('%', ''))
		colour_lightness     = int(colour_hsl[2].replace('%', ''))
		colour_hsl_formatted = 'hsl(%d, %d%%, %d%%)' % (colour_hue, colour_saturation, colour_lightness)

		# push to internal colour storage
		colour_storage.append([colour_name, colour_hsl_formatted])

	return colour_storage





# ----- Preview Circles ----- #

def make_cirles (colour_storage, colour_count):

	# create export directory
	if not os.path.exists('circles'):
		os.makedirs('circles')


	# setup progessbar
	toolbar_width = colour_count
	sys.stdout.write('\nGenerating Circles\n[%s]' % (' ' * toolbar_width))
	sys.stdout.flush()
	sys.stdout.write('\b' * (toolbar_width+1))


	for colour in colour_storage:

		# create canvas
		circle_canvas = Image.new('RGBA', (4000, 4000))

		# draw circle with current colour
		circle_canvas_draw = ImageDraw.Draw(circle_canvas)
		circle_canvas_draw.ellipse((0, 0, 3999, 3999), colour[1])

		# resize and export
		circle_colour_preview = circle_canvas.resize((40, 40))
		circle_colour_preview.save(f'circles/{colour[0]}.png')

		# update progessbar
		sys.stdout.write('=')
		sys.stdout.flush()

	# end progressbar
	sys.stdout.write(']\n')





# ----- .png Palette ----- #

def make_palette (colour_storage, colour_count):

	# setup progessbar
	toolbar_width = colour_count
	sys.stdout.write('\nGenerating .png Palette\n[%s]' % (' ' * toolbar_width))
	sys.stdout.flush()
	sys.stdout.write('\b' * (toolbar_width+1))


	pixel_size   = 16
	current_spot = 0
	png_canvas   = Image.new('RGBA', (colour_count*pixel_size, pixel_size))


	for colour in colour_storage:

		# create canvas
		png_canvas_draw = ImageDraw.Draw(png_canvas)

		# draw pixel
		png_canvas_draw.rectangle(((current_spot, 0), (current_spot+pixel_size, pixel_size)), colour[1])

		# update pixel position
		current_spot = current_spot+pixel_size

		# update progessbar
		sys.stdout.write('=')
		sys.stdout.flush()


	# export
	png_canvas.save('Catppuccin.png')

	# end progressbar
	sys.stdout.write(']\n')





# ----- Command Handler ----- #

def command_handler (args):

	# remove self
	script_name = args.pop(0)

	# help
	if any(arg in args for arg in ('-h', 'help')):

		print(f'Usage: {script_name} <command>\n')
		
		print('Commands')
		print('circles, -c     generate palette preview circles')
		print('palette, -p     generate .png palette file')
		print('help, -h        show this message')
		
		# terminate script if help is called
		return

	# populate globals
	colour_storage = read_source()
	colour_count   = len(colour_storage)
	
	# circles
	if any(arg in args for arg in ('-c', 'circles')):
		make_cirles(colour_storage, colour_count)

	# palette
	if any(arg in args for arg in ('-p', 'palette')):
		make_palette(colour_storage, colour_count)

	# default action
	if len(args) == 0:
		make_cirles(colour_storage, colour_count)
		make_palette(colour_storage, colour_count)





# ----- Please Run Me ----- #

if __name__ == '__main__':
	command_handler(sys.argv)
